### ISSUE TITLE
Chest builder doesn't work in Multiplayer

### ISSUE THREAD

**Issue by Simone-Righi-96** [Shadows-of-Fire/ComPatchedStorage#1]
Hello.

I'm having an issue with the ComPatchedStorage mod, but only in multiplayer ( i tried in singleplayer and it worked ).

Basically the Chest Builder doesn't let me create the chest, i have all the materials needed, but when i click on "Build", nothing happens, it just plays the error sound infinitely.

When i try to add them manually, one by one, the slot just empty itself and return the items on my inventory.

B.T.W. I'm playing Skyfactory 4.0.2 on a Custom private server

**Comment by Shadows-of-Fire** [comment]
Already fixed, you can manually update to compatched 1.5.1 to receive the fix.
