### ISSUE TITLE
Invisible items when opening a chest

### ISSUE THREAD

**Issue by hanno00** [Shadows-of-Fire/ComPatchedStorage#2]
When I open my chest (max-sized), I can see all my items, but when I pick up any of the stacks, all items become invisible. When I back out and go back in they are all visible.

**Comment by Shadows-of-Fire** [comment]
This has already been fixed, you're using an old version.

**Comment by hanno00** [comment]
Okay thanks, im using the version thats in Skyfactory 4, so I will update the mod myself
