### ISSUE TITLE
[1.14.4][Dedi-Svr] Inventory of backpack is cleared when switching to creative mode

### ISSUE THREAD

**Issue by MacAttack-UK** [Shadows-of-Fire/ComPatchedStorage#6]
When switching to creative mode the backpack inventory gets cleared. This also used to happened with the 1.12.2 version.

I'm currently using this in a test MP dedicated server with a number of other mods and it does not happen in SP.

I also have another backpack mod which this does not happen with.

forge-1.14.4-28.1.79
ComPatchedStorage-1.14.4-2.1.4

**Comment by Shadows-of-Fire** [comment]
This is caused by the following vanilla/forge issue: MinecraftForge/MinecraftForge#4580
Can't fix it from my end.

Any bag mod that does not experience the same issues is a vector for nbt packet oversize, which can also be considered a problem.
