### ISSUE TITLE
Change chest color afterwards

### ISSUE THREAD

**Issue by zipacna** [Shadows-of-Fire/ComPatchedStorage#7]
Is it possible to change the color of a chest after it was built under version 1.12.2-1.6.0 (forge-1.12.2-14.23.5.2838)?

Under any other version?

As a future update? Maybe similar to the color tool (BarrelsDrumsStorageAndMore-0.0.24, same forge)?

**Comment by Shadows-of-Fire** [comment]
The 1.12 version of CPS is a patch mod.  All content is handled by CompactStorage.
